---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fecoeror/boletos-app
    - /usr/local/bin/composer install --no-dev --working-dir=$DEPLOYPATH
    - /usr/local/bin/php $DEPLOYPATH/artisan key:generate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan storage:link